[package]
name = "create2-vanity"
version = "0.1.0"
edition = "2021"

[dependencies]
ethereum-types = "0.14"
keccak-hash = "0.10"
hex = "0.4"
rayon = "1.8"
rand = "0.8"
clap = { version = "4.4", features = ["derive"] }
serde_json = "1.0"
num_cpus = "1.16"
