[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@layerzerolabs/lz-evm-oapp-v2/=node_modules/@layerzerolabs/lz-evm-oapp-v2/",
    "@layerzerolabs/lz-evm-protocol-v2/=node_modules/@layerzerolabs/lz-evm-protocol-v2/",
    "@layerzerolabs/lz-evm-messagelib-v2/=node_modules/@layerzerolabs/lz-evm-messagelib-v2/",
    "@layerzerolabs/oapp-evm/=node_modules/@layerzerolabs/lz-evm-oapp-v2/",
    "@chainlink/=node_modules/@chainlink/",
    "forge-std/=node_modules/@layerzerolabs/toolbox-foundry/src/forge-std/src/",
    "solidity-bytes-utils/=node_modules/solidity-bytes-utils/",
    "lib/=lib/",
    "node_modules/=node_modules/"
]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "shanghai"

[profile.default.fuzz]
runs = 256

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 5_000 }

[rpc_endpoints]
sonic = "https://rpc.sonic.tech"
arbitrum = "https://arb1.arbitrum.io/rpc"
avalanche = "https://api.avax.network/ext/bc/C/rpc"

[etherscan]
sonic = { key = "${SONIC_API_KEY}", url = "https://api.sonicscan.org/api" }
arbitrum = { key = "${ARBITRUM_API_KEY}", url = "https://api.arbiscan.io/api" }
avalanche = { key = "${AVALANCHE_API_KEY}", url = "https://api.snowtrace.io/api" } 